## Regression Model Selection

1.   Use the learned Regression Models so far and select the best one based on their performance result.
2.   **Input** = Data.csv 

UCI ML repository





## Importing the libraries

In [53]:
import numpy as np
import matplotlib.pyplot as plt       #graphs
import pandas as pd

# Importing the dataset

In [54]:
dataset = pd.read_csv('Data.csv')
XMLR = dataset.iloc[:, 1:-1].values      #There is no need to use the column Position
XPR = dataset.iloc[:, 1:-1].values      #There is no need to use the column Position
XSVR = dataset.iloc[:, 1:-1].values      #There is no need to use the column Position
XDTR = dataset.iloc[:, 1:-1].values      #There is no need to use the column Position
XRFR = dataset.iloc[:, 1:-1].values      #There is no need to use the column Position
yMLR = dataset.iloc[:,-1].values
yPR = dataset.iloc[:,-1].values
ySVR = dataset.iloc[:,-1].values
yDTR = dataset.iloc[:,-1].values
yRFR = dataset.iloc[:,-1].values



##Creating the models

1) Multiple Linear Regression

In [55]:
# Multiple Linear Regression: Split dataset into Traning and Test sets
from sklearn.model_selection import train_test_split
X_trainMLR, X_testMLR, y_trainMLR, y_testMLR = train_test_split(XMLR, yMLR, test_size = 0.2, random_state = 0)

2) Polynomial Regression

In [56]:
# Polynomial Regression
from sklearn.model_selection import train_test_split
X_trainPR, X_testPR, y_trainPR, y_testPR = train_test_split(XPR, yPR, test_size = 0.2, random_state = 0)

3) Support Vector Regression (SVR)

In [57]:
y_SVR = ySVR.reshape(len(y),1)

In [58]:
from sklearn.model_selection import train_test_split
X_trainSVR, X_testSVR, y_trainSVR, y_testSVR = train_test_split(XSVR,y_SVR, test_size=0.2, random_state = 0)

4) Decision Tree Regression

In [59]:
from sklearn.model_selection import train_test_split
X_trainDTR, X_testDTR, y_trainDTR, y_testDTR = train_test_split(XDTR, yDTR, test_size=0.2, random_state =0)

5) Random Forest Regression

In [60]:
from sklearn.model_selection import train_test_split
X_trainRFR, X_testRFR, y_trainRFR, y_testRFR = train_test_split(XRFR, yRFR, test_size=0.2, random_state =0)

# Feature Scaling

3) SVR

In [61]:
from sklearn.preprocessing import StandardScaler
sc_xSVR = StandardScaler()
sc_ySVR = StandardScaler()
X_trainSVR = sc_xSVR.fit_transform(X_trainSVR)
y_trainSVR = sc_ySVR.fit_transform(y_trainSVR)

# Training the Regressions model on the whole dataset

1) Multiple Linear Regression

In [62]:
from sklearn.linear_model import LinearRegression
regressorMLR = LinearRegression()
regressorMLR.fit(X_trainMLR, y_trainMLR)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

2) Polynomial Regression

In [63]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
polyRegress = PolynomialFeatures(degree = 4)
X_PR = polyRegress.fit_transform(X_trainPR)
regressorPR = LinearRegression()
regressorPR.fit(X_PR, y_trainPR)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

3) SVR

In [64]:
from sklearn.svm import SVR
regressorSVR = SVR(kernel = 'rbf')
regressorSVR.fit(X_trainSVR, y_trainSVR)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

4) Decision Tree Regression

In [65]:
from sklearn.tree import DecisionTreeRegressor
regressorDTR = DecisionTreeRegressor(random_state = 0)
regressorDTR.fit(X_trainDTR,y_trainDTR)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

5) Random Forest Regression

In [66]:
from sklearn.ensemble import RandomForestRegressor
regressorRFR = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressorRFR.fit(X_trainRFR, y_trainRFR)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

# Predicting a new result

1) Multiple Linear Regression

In [67]:
y_predMLR = regressorMLR.predict(X_testMLR)
np.set_printoptions(precision=2)
print(np.concatenate((y_predMLR.reshape(len(y_predMLR),1), y_testMLR.reshape(len(y_testMLR),1)),1))

[[428.05 431.23]
 [465.79 460.01]
 [473.08 461.14]
 ...
 [472.1  473.26]
 [453.04 438.  ]
 [465.42 463.28]]


2) Polynomial Regression

In [68]:
y_predPR = regressorPR.predict(polyRegress.fit_transform(X_testPR))
np.set_printoptions(precision=2)
print(np.concatenate((y_predPR.reshape(len(y_predPR),1), y_testPR.reshape(len(y_testPR),1)),1))

[[431.06 431.23]
 [463.38 460.01]
 [470.46 461.14]
 ...
 [470.29 473.26]
 [443.2  438.  ]
 [466.89 463.28]]


3) SVR

In [69]:
y_predSVR = sc_ySVR.inverse_transform(regressorSVR.predict(sc_xSVR.transform(X_testSVR)))
np.set_printoptions(precision=2)
print(np.concatenate((y_predSVR.reshape(len(y_predSVR),1), y_testSVR.reshape(len(y_testSVR),1)),1))

[[432.98 431.23]
 [460.91 460.01]
 [468.67 461.14]
 ...
 [468.91 473.26]
 [442.3  438.  ]
 [464.64 463.28]]


4) Decision Tree Regression

In [70]:
y_predDTR = regressorDTR.predict(X_testDTR)
np.set_printoptions(precision=2)
print(np.concatenate((y_predDTR.reshape(len(y_predDTR),1), y_testDTR.reshape(len(y_testDTR),1)),1))

[[432.84 431.23]
 [460.   460.01]
 [469.73 461.14]
 ...
 [471.43 473.26]
 [438.61 438.  ]
 [461.7  463.28]]


5) Random Forest Regression

In [71]:
y_predRFR = regressorRFR.predict(X_testRFR)
np.set_printoptions(precision=2)
print(np.concatenate((y_predRFR.reshape(len(y_predRFR),1), y_testRFR.reshape(len(y_testRFR),1)),1))

[[434.6  431.23]
 [458.76 460.01]
 [469.48 461.14]
 ...
 [472.41 473.26]
 [440.22 438.  ]
 [463.56 463.28]]


## Evaluating the Model Performance

1) Multiple Linear Regression

In [72]:
from sklearn.metrics import r2_score
r2_score(y_testMLR, y_predMLR)

0.8033292150759015

2) Polynomial Regression

In [73]:
from sklearn.metrics import r2_score
r2_score(y_testPR, y_predPR)

0.8418720530590948

3) SVR

In [74]:
from sklearn.metrics import r2_score
r2_score(y_testSVR, y_predSVR)

0.8494246102002505

4) Decision Tree

In [75]:
from sklearn.metrics import r2_score
r2_score(y_testDTR, y_predDTR)

0.8783798803904339

5) Random Forest

In [76]:
from sklearn.metrics import r2_score
r2_score(y_testRFR, y_predRFR)

0.9348788182361043