## Artificial Neural Network

1.   Apply the ANN with Tensorflow to classify bank customers information to determine if the customer exited the bank

2.   **Input** = Churn_Modelling.csv






## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf 

In [3]:
tf.__version__

'2.7.0'

# Part 1 - Data Preprocessing

## Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
x = dataset.iloc[:, 3:-1].values #Excludes index, ID, and Surname
y = dataset.iloc[:, -1].values

In [6]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding categorical data

### Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [9]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


###Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder #Create a matrix for the countries
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


##Splitting the dataset into the Training set and Test set


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

##Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [15]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


#Part 2 - Buildig the ANN

##Initializing the ANN

In [16]:
ann = tf.keras.Sequential()

##Adding the input layer and the first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#Part 3 - Training the ANN

## Compiling the ANN

In [20]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Training the ANN on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size=32, epochs=100) #32 is a default parameter for batch size...

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5837 - accuracy: 0.7013
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4580 - accuracy: 0.8077
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4342 - accuracy: 0.8144
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4210 - accuracy: 0.8196
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4086 - accuracy: 0.8253
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3951 - accuracy: 0.8336
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3830 - accuracy: 0.8391
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3732 - accuracy: 0.8445
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3659 - accuracy: 0.8462
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3611 - accura

# Part 4 - making the predictions and evaluating the model

## Predicting the result of a single observation

Predict the outcome of a customer

Geo: France,

Credit Score: 600,

Gender: Male ,

Age: 40 years old,

Tenure: 3 years,    

Balance: $60000,

Number of Products: 2,

Credit Card? Yes,

Estimated Salary: $50000 ,

In [24]:
print(ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1 , 1, 50000]])) > 0.5)

[[False]]


## Predicting the test

In [25]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) # converts the prob into true/false
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
# [[Correct Incorrect] 
#  [Incorrect Correct]]
acc = accuracy_score(y_test,y_pred)
print(acc)

[[1520   75]
 [ 199  206]]
0.863
